apiVersion: vitu.dev/v1alpha1
kind: Kluster
metadata:
  name: kluster-0
spec:
  name: kluster-0
  region: "sgp1"
  version: "1.25.4-do.0"
  tokenSecret: "default/dosecret"
  nodePools:
    - count: 3
      name: "dummy-nodepool"
      size: "s-1vcpu-2gb"
